/**
 * ResourceController.java
 *
 * REST controller that exposes HTTP endpoints for managing emergency resources
 * within the Disaster Management System (DMS). Resources represent physical
 * assets used during disaster response — such as ambulances, fire trucks,
 * rescue equipment, shelters, and medical supplies.
 *
 * This controller handles full CRUD operations plus specialized actions like
 * status updates and assigning resources to active incidents. Access to
 * mutating operations is restricted to RESCUE_TEAM and ADMIN roles, while
 * deletion is limited to ADMIN only, ensuring proper command hierarchy during
 * emergency operations.
 *
 * All endpoints are versioned under /api/v1/resources and return responses
 * wrapped in the standard ApiResponse envelope for consistent client handling.
 */
package com.dms.resource;

// Imports the standard DMS API response wrapper used across all controllers
import com.dms.common.ApiResponse;
// Swagger/OpenAPI annotations for auto-generating API documentation
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
// Lombok annotation that generates a constructor for all final fields (dependency injection)
import lombok.RequiredArgsConstructor;
// Spring Data pagination support for returning large resource lists in chunks
import org.springframework.data.domain.Page;
// Spring HTTP response wrapper allowing custom status codes and headers
import org.springframework.http.ResponseEntity;
// Enables method-level security using SpEL expressions (role checks before execution)
import org.springframework.security.access.prepost.PreAuthorize;
// Spring MVC annotations for defining RESTful endpoints and binding HTTP data
import org.springframework.web.bind.annotation.*;

// Used to return a flat list of all resources for legacy map component consumption
import java.util.List;

// Marks this class as a REST controller — combines @Controller + @ResponseBody,
// so all return values are serialized directly to JSON in the HTTP response body
@RestController
// Maps all endpoints in this class under the versioned /api/v1/resources base path
@RequestMapping("/api/v1/resources")
// Lombok: generates a constructor injecting ResourceService via the final field below
@RequiredArgsConstructor
// Swagger grouping tag — labels this controller "Resources" in the OpenAPI UI with a description
@Tag(name = "Resources", description = "Emergency resource management")
public class ResourceController {

    // Service layer responsible for all resource business logic and database operations;
    // injected via constructor (generated by @RequiredArgsConstructor) — not instantiated here
    private final ResourceService resourceService;

    // Handles GET /api/v1/resources — supports both paginated and flat-list modes
    @GetMapping
    // Swagger: documents this endpoint's purpose in the generated API explorer
    @Operation(summary = "Get all resources (paginated)")
    public ResponseEntity<ApiResponse<?>> getAllResources(
            // Zero-based page index; defaults to 0 (first page) if not supplied by the client
            @RequestParam(defaultValue = "0")  int page,
            // Number of resources per page; defaults to 20 to keep response payloads manageable
            @RequestParam(defaultValue = "20") int size,
            // Optional filter by resource type (e.g. "AMBULANCE", "FIRE_TRUCK") — null means no filter
            @RequestParam(required = false) String type,
            // Optional filter by availability status (e.g. "AVAILABLE", "DEPLOYED") — null means no filter
            @RequestParam(required = false) String status) {

        // Legacy compatibility branch: when called with default params and no filters,
        // return the full flat list so that map components (which iterate all markers) still work
        if (page == 0 && size == 20 && type == null && status == null) {
            // Legacy: return flat list for map components
            // Fetch every resource without pagination for backward-compatible map rendering
            List<ResourceDTO> all = resourceService.getAllResources();
            // Wrap the list in ApiResponse and return HTTP 200 OK
            return ResponseEntity.ok(ApiResponse.ok(all));
        }
        // Paginated path: fetch only the requested page slice with optional type/status filters
        Page<ResourceDTO> result = resourceService.getResourcesPage(page, size, type, status);
        // Return the Page object (includes metadata: totalElements, totalPages, etc.) wrapped in ApiResponse
        return ResponseEntity.ok(ApiResponse.ok(result));
    }

    // Handles GET /api/v1/resources/{id} — retrieves a single resource by its unique database ID
    @GetMapping("/{id}")
    // Swagger: labels this endpoint in the API documentation
    @Operation(summary = "Get resource by ID")
    public ResponseEntity<ApiResponse<ResourceDTO>> getById(
            // Extracts the {id} path segment and binds it to the Long parameter
            @PathVariable Long id) {
        // Fetches the full resource list and streams through it to find the matching ID;
        // throws ResourceNotFoundException (mapped to HTTP 404) if no resource matches
        return ResponseEntity.ok(ApiResponse.ok(resourceService.getAllResources().stream()
            .filter(r -> r.getId().equals(id)).findFirst()
            .orElseThrow(() -> new com.dms.exception.ResourceNotFoundException("Resource not found: " + id))));
    }

    // Handles POST /api/v1/resources — creates a new emergency resource record
    @PostMapping
    // Security: only authenticated users with RESCUE_TEAM or ADMIN role may register new resources
    @PreAuthorize("hasAnyRole('RESCUE_TEAM','ADMIN')")
    // Swagger: documents the create-resource endpoint
    @Operation(summary = "Create resource")
    public ResponseEntity<ApiResponse<ResourceDTO>> createResource(
            // Deserializes the JSON request body into a ResourceDTO (name, type, location, capacity, etc.)
            @RequestBody ResourceDTO request) {
        // Delegates creation to the service layer and returns HTTP 201 Created with the persisted resource
        return ResponseEntity.status(201).body(ApiResponse.created(resourceService.createResource(request), "Resource created"));
    }

    // Handles PUT /api/v1/resources/{id} — fully replaces an existing resource's data
    @PutMapping("/{id}")
    // Security: only RESCUE_TEAM or ADMIN roles may modify existing resource records
    @PreAuthorize("hasAnyRole('RESCUE_TEAM','ADMIN')")
    // Swagger: labels the update endpoint in API docs
    @Operation(summary = "Update resource")
    public ResponseEntity<ApiResponse<ResourceDTO>> updateResource(
            // Extracts the target resource ID from the URL path
            @PathVariable Long id,
            // Deserializes the updated resource data from the request body
            @RequestBody ResourceDTO request) {
        // Delegates the update to the service and returns the refreshed resource wrapped in HTTP 200 OK
        return ResponseEntity.ok(ApiResponse.ok(resourceService.updateResource(id, request), "Resource updated"));
    }

    // Handles PATCH /api/v1/resources/{id}/status — lightweight partial update for availability status
    // (e.g. marking a resource as DEPLOYED, IN_MAINTENANCE, or AVAILABLE without resending full data)
    @PatchMapping("/{id}/status")
    // Security: status transitions should only be made by field teams or administrators
    @PreAuthorize("hasAnyRole('RESCUE_TEAM','ADMIN')")
    // Swagger: documents the status-update patch endpoint
    @Operation(summary = "Update resource status")
    public ResponseEntity<ApiResponse<ResourceDTO>> updateStatus(
            // ID of the resource whose operational status is being changed
            @PathVariable Long id,
            // New status value as a query parameter (e.g. ?status=AVAILABLE)
            @RequestParam String status) {
        // Calls the service to persist the new status and returns the updated resource
        return ResponseEntity.ok(ApiResponse.ok(resourceService.updateStatus(id, status), "Status updated"));
    }

    // Handles PATCH /api/v1/resources/{id}/assign — links a resource to a specific active incident
    // so dispatchers can track which assets are committed to which disaster event
    @PatchMapping("/{id}/assign")
    // Security: only RESCUE_TEAM members or ADMIN can dispatch resources to incidents
    @PreAuthorize("hasAnyRole('RESCUE_TEAM','ADMIN')")
    // Swagger: documents the assign-to-incident endpoint
    @Operation(summary = "Assign resource to incident")
    public ResponseEntity<ApiResponse<ResourceDTO>> assignToIncident(
            // ID of the resource being dispatched
            @PathVariable Long id,
            // ID of the target incident this resource is being assigned to (e.g. ?incidentId=42)
            @RequestParam Long incidentId) {
        // Delegates the assignment logic to the service (validates both IDs and updates the FK relationship)
        return ResponseEntity.ok(ApiResponse.ok(resourceService.assignResourceToIncident(id, incidentId), "Resource assigned"));
    }

    // Handles DELETE /api/v1/resources/{id} — permanently removes a resource record from the system
    @DeleteMapping("/{id}")
    // Security: deletion is an irreversible action restricted to ADMIN role only
    @PreAuthorize("hasRole('ADMIN')")
    // Swagger: documents the delete endpoint
    @Operation(summary = "Delete resource")
    public ResponseEntity<ApiResponse<Void>> deleteResource(
            // ID of the resource to permanently delete
            @PathVariable Long id) {
        // Instructs the service to remove the resource; service may throw if ID does not exist
        resourceService.deleteResource(id);
        // Return HTTP 200 OK with a null data body and a confirmation message
        return ResponseEntity.ok(ApiResponse.ok(null, "Resource deleted"));
    }
}