/**
 * NotificationDTO.java
 *
 * Data Transfer Object for conveying notification data between the DMS backend layers
 * and the frontend clients (citizen portal, officer dashboard, admin panel).
 *
 * This DTO shields internal entity details (e.g., JPA annotations, database IDs) from
 * API consumers, exposing only the fields needed to render alert banners, push
 * notifications, and in-app notification panels related to incidents, resources, and
 * system events.
 *
 * Used in REST responses for endpoints such as GET /api/notifications and
 * PATCH /api/notifications/{id}/read.
 */
package com.dms.notification;

// Lombok imports: generate boilerplate (getters, setters, builder, constructors) at compile time
import lombok.*;
// Java time API: represents precise timestamps for notification lifecycle tracking
import java.time.LocalDateTime;

// @Data: generates getters, setters, equals, hashCode, and toString for all fields
@Data
// @Builder: enables fluent builder pattern used in fromEntity() to construct instances cleanly
@Builder
// @NoArgsConstructor: required by frameworks (e.g., Jackson) that deserialize JSON into this DTO
@NoArgsConstructor
// @AllArgsConstructor: generated by @Builder internally; also useful for manual construction in tests
@AllArgsConstructor
public class NotificationDTO {

    // Unique identifier of the notification record in the DMS database
    private Long id;

    // ID of the DMS user (citizen, officer, or admin) this notification targets
    private Long userId;

    // Short headline of the notification, e.g., "Incident Assigned" or "Resource Deployed"
    private String title;

    // Full descriptive body of the notification delivered to the user's notification panel
    private String message;

    // Category/type of notification (e.g., "INCIDENT_ALERT", "SYSTEM", "RESOURCE_UPDATE")
    // used by the frontend to apply appropriate icons and urgency styling
    private String type;

    // Tracks whether the user has acknowledged/read this notification; drives unread badge count
    private Boolean isRead;

    // Timestamp recording exactly when the user marked this notification as read;
    // null if the notification has not yet been read
    private LocalDateTime readAt;

    // Timestamp of when this notification was originally created and dispatched in the DMS
    private LocalDateTime createdAt;

    /**
     * Factory method that converts a {@link Notification} JPA entity into a
     * {@link NotificationDTO} safe for API serialization.
     *
     * Mapping is done field-by-field to decouple the persistence model from the
     * transport model, preventing accidental exposure of internal entity state.
     *
     * @param notification the persisted Notification entity retrieved from the database
     * @return a fully populated NotificationDTO ready to be returned in an HTTP response
     */
    public static NotificationDTO fromEntity(Notification notification) {
        return NotificationDTO.builder()
            // Map the entity's primary key to the DTO's id field
            .id(notification.getNotificationId())
            // Preserve the target user reference so the frontend can filter by recipient
            .userId(notification.getUserId())
            // Carry over the notification headline
            .title(notification.getTitle())
            // Carry over the full notification body text
            .message(notification.getMessage())
            // Carry over the notification category for frontend rendering logic
            .type(notification.getType())
            // Carry over the read/unread state to drive UI badge counts
            .isRead(notification.getIsRead())
            // Carry over the timestamp of when the notification was read (may be null)
            .readAt(notification.getReadAt())
            // Carry over the creation timestamp for display in notification history panels
            .createdAt(notification.getCreatedAt())
            // Finalise and construct the DTO instance via the Lombok builder
            .build();
    }
}