/**
 * Notification.java
 *
 * JPA entity representing an in-system notification delivered to DMS users.
 * Notifications are generated by the system to alert users (citizens, officers,
 * administrators) about incident updates, resource assignments, status changes,
 * or general platform announcements. Each record is persisted in the
 * "notifications" table and tracks delivery state (read/unread).
 */
package com.dms.notification;

// --- Jakarta Persistence imports for ORM mapping to the database ---
import jakarta.persistence.*;
// --- Lombok annotations to eliminate boilerplate getters/setters/builders ---
import lombok.*;
// --- Hibernate extension that auto-populates the creation timestamp ---
import org.hibernate.annotations.CreationTimestamp;

// --- Java time API for recording when the notification was created and read ---
import java.time.LocalDateTime;

// Marks this class as a JPA-managed database entity mapped to the "notifications" table
@Entity
// Explicitly names the database table that stores DMS notification records
@Table(name = "notifications")
// @Data: generates getters, setters, equals, hashCode, and toString via Lombok
// @Builder: enables the builder pattern for constructing Notification instances
// @NoArgsConstructor: required by JPA — provides a no-argument constructor
// @AllArgsConstructor: provides a constructor accepting all fields, used by @Builder internally
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class Notification {

    // Primary key of the notification record; auto-incremented by the database
    @Id
    // Delegates ID generation to the database identity/sequence strategy
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Maps this field to the "notification_id" column in the notifications table
    @Column(name = "notification_id")
    private Long notificationId;

    // References the DMS user (citizen, officer, or admin) who should receive this notification
    // NOT a foreign-key JPA relationship — kept as a plain Long for lightweight queries
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // Short headline of the notification (e.g., "Incident Status Updated", "Resource Assigned")
    @Column(nullable = false)
    private String title;

    // Full notification body; stored as TEXT to accommodate detailed incident or alert descriptions
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    // Categorises the notification for UI rendering and filtering:
    // common values include "INFO", "WARNING", "ALERT", "SUCCESS"
    @Column(nullable = false)
    // @Builder.Default ensures the builder sets "INFO" when no type is explicitly provided
    @Builder.Default
    private String type = "INFO";

    // Tracks whether the recipient has read this notification in the DMS portal
    @Column(name = "is_read", nullable = false)
    // @Builder.Default ensures newly created notifications start as unread
    @Builder.Default
    private Boolean isRead = false;

    // Records the exact moment the user acknowledged/read the notification; null until read
    @Column(name = "read_at")
    private LocalDateTime readAt;

    // Automatically set by Hibernate to the database server time when the row is inserted;
    // never updated after creation, providing an immutable audit timestamp
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Marks this notification as read by the recipient.
     *
     * Called when the DMS user opens or acknowledges the notification in the UI.
     * Sets the read flag to true and stamps the current time as the read timestamp,
     * enabling audit trails and unread-count calculations across the platform.
     */
    public void markAsRead() {
        // Flag the notification as having been seen by the user
        this.isRead = true;
        // Capture the exact moment the user read the notification for auditing purposes
        this.readAt = LocalDateTime.now();
    }
}