/**
 * HistoricalReport.java
 *
 * Represents a historical report entity in the Disaster Management System (DMS).
 * Historical reports are administrative summaries generated over a specified date range,
 * capturing aggregated incident data, resource usage, and operational outcomes.
 * These reports are created by admins to support post-disaster analysis, compliance,
 * and strategic planning. Each report is persisted in the "historical_reports" table.
 */
package com.dms.report;

// Import the Admin entity to associate each report with the admin who generated it
import com.dms.admin.Admin;

// Jakarta Persistence API annotations for ORM mapping to the database
import jakarta.persistence.*;

// Lombok annotations to auto-generate boilerplate: getters, setters, builder, constructors
import lombok.*;

// Hibernate-specific annotation for automatic timestamp on record creation
import org.hibernate.annotations.CreationTimestamp;

// Date types for capturing the reporting period and generation timestamp
import java.time.LocalDate;
import java.time.LocalDateTime;

// @Entity marks this class as a JPA-managed entity mapped to a database table
@Entity
// @Table specifies the database table name that stores historical report records
@Table(name = "historical_reports")
// @Data generates getters, setters, equals, hashCode, and toString via Lombok
// @Builder enables the builder pattern for constructing HistoricalReport instances
// @NoArgsConstructor generates a no-argument constructor required by JPA
// @AllArgsConstructor generates a constructor with all fields for programmatic use
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class HistoricalReport {

    // @Id designates this field as the primary key of the historical_reports table
    @Id
    // @GeneratedValue with IDENTITY strategy lets the database auto-increment the report ID
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Maps this field to the "report_id" column in the database
    @Column(name = "report_id")
    // Unique identifier for each historical report record
    private Long reportId;

    // Stores a free-text summary describing the disaster events and outcomes within the report period
    // TEXT column type allows long-form narrative content beyond VARCHAR limits
    @Column(nullable = false, columnDefinition = "TEXT")
    // Narrative summary of incidents, responses, and outcomes covered in this report
    private String summary;

    // Maps to "start_date" column; defines the beginning of the reporting period (inclusive)
    @Column(name = "start_date", nullable = false)
    // The first date of the period covered by this historical report
    private LocalDate startDate;

    // Maps to "end_date" column; defines the end of the reporting period (inclusive)
    @Column(name = "end_date", nullable = false)
    // The last date of the period covered by this historical report
    private LocalDate endDate;

    // @CreationTimestamp automatically sets this field to the current timestamp when the entity is first persisted
    @CreationTimestamp
    // updatable = false ensures the generation timestamp is never modified after initial insert
    @Column(name = "generated_at", nullable = false, updatable = false)
    // The exact date and time when this report was generated by the DMS system
    private LocalDateTime generatedAt;

    // Optional link to a stored file (e.g., PDF or Excel export) for download or archival
    @Column(name = "file_link")
    // URL or file path to the exported report document; nullable since not all reports produce a file
    private String fileLink;

    // Maps to "total_incidents" column; tracks the count of disaster incidents in this report's date range
    @Column(name = "total_incidents", nullable = false)
    // @Builder.Default ensures the field defaults to 0 when using the Lombok builder without specifying a value
    @Builder.Default
    // Total number of disaster incidents recorded during the report's date range
    private Integer totalIncidents = 0;

    // @ManyToOne indicates many reports can be associated with one admin; LAZY fetch avoids loading admin data unless needed
    @ManyToOne(fetch = FetchType.LAZY)
    // @JoinColumn specifies the foreign key column "admin_id" linking this report to the admins table
    @JoinColumn(name = "admin_id")
    // The admin who generated or is responsible for this historical report; nullable to support system-generated reports
    private Admin admin;
}