// ============================================================================
// notification_model.dart
//
// Data model for DMS push/in-app notifications delivered to field officers,
// team members, and administrators. Each notification may relate to a
// specific disaster incident and carries a read/unread status so the UI
// can badge unread alerts and mark them read after the user views them.
//
// The model maps directly onto the backend AlertDTO JSON payload produced
// by the Spring Boot alert service. A key serialization quirk is that
// Java's boolean getter `isRead()` is serialized by Jackson as the JSON
// field `"read"` (not `"isRead"`), which this model handles explicitly.
// ============================================================================

/// Immutable data model representing a single DMS notification/alert.
///
/// Notifications are generated by the backend when incident status changes,
/// new resources are assigned, or system-level alerts are broadcast to users.
class NotificationModel {
  /// Unique identifier assigned by the backend database (maps to AlertDTO.id).
  final int id;

  /// Short headline for the notification, e.g. "New Incident Reported".
  final String title;

  /// Full notification body describing the alert or incident update.
  final String message;

  /// Optional category tag (e.g. "INCIDENT", "RESOURCE", "SYSTEM") used
  /// to route notifications to the correct UI section or icon.
  final String? type;

  // AlertDTO Java getter isRead() serializes as 'read' in JSON —
  // the fromJson factory compensates for both key names for resilience.
  /// Whether the notification has been read by the recipient.
  /// Drives the unread badge count and visual highlight in the notification list.
  final bool isRead;

  /// ISO-8601 timestamp string from the backend indicating when the alert
  /// was created. Nullable because legacy records may omit this field.
  final String? createdAt;

  /// Optional reference to the disaster incident this notification concerns.
  /// Non-null when the alert is tied to a specific incident so the UI can
  /// deep-link the user directly to the IncidentDetail screen.
  final int? incidentId;

  /// Creates a [NotificationModel] with all fields supplied explicitly.
  /// Declared `const` to allow compile-time constant instances in tests/stubs.
  const NotificationModel({
    required this.id,
    required this.title,
    required this.message,
    this.type,       // optional — not all alerts have a category tag
    required this.isRead,
    this.createdAt,  // optional — may be absent in older backend responses
    this.incidentId, // optional — system-wide alerts are not tied to an incident
  });

  /// Deserializes a [NotificationModel] from a JSON map returned by the
  /// DMS backend alert endpoint (e.g. GET /api/alerts).
  ///
  /// Handles two defensive concerns:
  ///  1. Numeric type coercion — `id` and `incidentId` may arrive as [num]
  ///     instead of [int] depending on the JSON decoder, so both are cast safely.
  ///  2. Dual read-field support — Jackson serializes `isRead()` as `"read"`,
  ///     but older clients may send `"isRead"`. Both keys are checked in order.
  factory NotificationModel.fromJson(Map<String, dynamic> json) =>
      NotificationModel(
        // Safely coerce id: treat raw int directly, otherwise cast from num
        // to avoid a runtime type error when the JSON decoder returns double.
        id: (json['id'] ?? 0) is int
            ? json['id'] ?? 0
            : (json['id'] as num).toInt(),

        // Fall back to empty string so the UI never renders a null title.
        title: json['title'] ?? '',

        // Fall back to empty string so the notification body is never null.
        message: json['message'] ?? '',

        // Convert to String explicitly in case the backend sends a numeric code.
        type: json['type']?.toString(),

        // Java isRead() → JSON field 'read'; also accept 'isRead' for compatibility
        // with any client or mock that uses the Dart-style field name.
        isRead: json['read'] ?? json['isRead'] ?? false,

        // Convert to String in case timestamp arrives as a non-string type.
        createdAt: json['createdAt']?.toString(),

        // Nullable int coercion: skip cast entirely if the field is absent.
        incidentId: json['incidentId'] is int
            ? json['incidentId']
            : (json['incidentId'] as num?)?.toInt(),
      );
}